#Author: TALMASH

include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-tinyfecvpn-easyconf
LUCI_Title:=TinyFEC VPN cloud-init automated configuration
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+libuci +luci-compat
PKG_VERSION:=1.1
PKG_RELEASE:=2

PKG_MAINTANINER:=Brazzo97
PKG_LICENSE:=BSD
PKG_LICENSE_FILES:=LICENSE


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
